export enum Enum_BotActionCode {
  FIND_ORDER_BY_ID = "FIND_ORDER_BY_ID",
  GET_CUSTOMERS_REGISTERED_TODAY = "GET_CUSTOMERS_REGISTERED_TODAY",
  GET_TOTAL_ORDERS_TODAY = "GET_TOTAL_ORDERS_TODAY",
  GET_GROSS_REVENUE_TODAY = "GET_GROSS_REVENUE_TODAY",
  GET_PENDING_ORDERS = "GET_PENDING_ORDERS",
}
